public class Test{
    public static void main(String[] args){
        try {
            System.out.println(caculate(10, 0));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public static int caculate(int x, int y) throws Exception{
        int ret = 0;
        System.out.println("1.计算开始前****");
        try {
            ret = x / y;
        } catch (Exception e) {
            throw e;
        }finally{
            System.out.println("2.计算结束####");
        }
        return ret;
    }
}
